spring.application.name=energy-producer

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
weather.latitude=48.2082
weather.longitude=16.3738

spring.main.web-application-type=none